# Generated by Django 4.2.3 on 2023-09-28 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_App', '0002_user_image_user_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_purchasemanger',
            new_name='is_purchasemanager',
        ),
    ]
