# Generated by Django 4.2.3 on 2023-09-30 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_App', '0003_rename_is_purchasemanger_user_is_purchasemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_distributor',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, max_length=15, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address_one', models.CharField(blank=True, max_length=150, null=True)),
                ('address_two', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('education', models.CharField(blank=True, max_length=25, null=True)),
                ('education_description', models.CharField(blank=True, max_length=250, null=True)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_number', models.CharField(blank=True, max_length=50, null=True)),
                ('father_job', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_number', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_job', models.CharField(blank=True, max_length=50, null=True)),
                ('friend_one_name', models.CharField(blank=True, max_length=50, null=True)),
                ('friend_one_number', models.CharField(blank=True, max_length=50, null=True)),
                ('friend_one_job', models.CharField(blank=True, max_length=50, null=True)),
                ('friend_two_name', models.CharField(blank=True, max_length=50, null=True)),
                ('friend_two_number', models.CharField(blank=True, max_length=50, null=True)),
                ('friend_two_job', models.CharField(blank=True, max_length=50, null=True)),
                ('distribution_area', models.CharField(blank=True, max_length=50, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=50, null=True)),
                ('aadhaar_image', models.ImageField(blank=True, null=True, upload_to='aadhaar-image')),
                ('pan_card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_card_image', models.ImageField(blank=True, null=True, upload_to='pan-card-image')),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_branch_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_holder_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_ifc_code', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
