# Generated by Django 4.2.3 on 2023-10-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_App', '0004_user_is_distributor_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='education',
            field=models.CharField(blank=True, choices=[('SSLC', 'SSLC'), ('Plus Two', 'Plus Two'), ('Degree', 'Degree'), ('PG', 'PG')], max_length=25, null=True),
        ),
    ]
